# Generated by Django 3.2.18 on 2023-05-09 15:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shirt', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shirt',
            name='photo',
        ),
    ]
