# Generated by Django 3.2.18 on 2023-05-17 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shirt', '0003_auto_20230517_1157'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shirt',
            name='color',
            field=models.CharField(max_length=50),
        ),
    ]
