# Generated by Django 3.2.18 on 2023-05-19 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shirt', '0010_alter_shirt_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='shirt',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='shirt',
            name='deleted_at',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
