# Generated by Django 3.2.18 on 2023-05-19 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shirt', '0011_auto_20230519_1303'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shirt',
            name='name',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
