# Generated by Django 3.2.18 on 2023-05-19 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shirt', '0012_alter_shirt_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shirt',
            name='name',
            field=models.CharField(default='proof', max_length=20),
            preserve_default=False,
        ),
    ]
