# Generated by Django 3.2.18 on 2023-05-22 20:02

import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('shirt', '0014_alter_shirt_name'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='shirt',
            managers=[
                ('active_objects', django.db.models.manager.Manager()),
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.AlterField(
            model_name='shirt',
            name='name',
            field=models.CharField(max_length=20),
        ),
    ]
