# Generated by Django 3.2.18 on 2023-05-22 20:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shirt', '0015_auto_20230522_2202'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='shirt',
            managers=[
            ],
        ),
    ]
