# Generated by Django 3.2.18 on 2023-05-31 15:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ejercicios', '0002_alter_nevera_id'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Nevera',
        ),
        migrations.DeleteModel(
            name='Television',
        ),
    ]
