# Generated by Django 3.2.18 on 2023-05-31 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ejercicios', '0004_nevera_television'),
    ]

    operations = [
        migrations.AlterField(
            model_name='television',
            name='numero_de_serie',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
