# Generated by Django 3.2.18 on 2023-06-05 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ejercicios', '0005_alter_television_numero_de_serie'),
    ]

    operations = [
        migrations.AddField(
            model_name='nevera',
            name='marca',
            field=models.CharField(default='Bosh', max_length=100),
        ),
        migrations.AddField(
            model_name='nevera',
            name='nombre',
            field=models.CharField(default='Proof', max_length=100),
        ),
    ]
