# Generated by Django 3.2.18 on 2023-06-05 16:45

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('ejercicios', '0006_auto_20230605_1819'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comentario',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, default=None, null=True)),
                ('active', models.BooleanField(default=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('publicacion', models.IntegerField()),
                ('usuario', models.CharField(max_length=100)),
                ('comentario', models.CharField(max_length=1000)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
