# Generated by Django 3.2.18 on 2023-06-07 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ejercicios', '0008_alter_nevera_marca'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nevera',
            name='marca',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
