# Generated by Django 3.2.18 on 2023-06-07 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ejercicios', '0009_alter_nevera_marca'),
    ]

    operations = [
        migrations.AddField(
            model_name='nevera',
            name='vendido',
            field=models.BooleanField(default=True),
        ),
    ]
