# Generated by Django 3.2.18 on 2023-06-07 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ejercicios', '0011_alter_nevera_vendido'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nevera',
            name='vendido',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
