# Generated by Django 3.2.18 on 2023-06-27 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shirt', '0021_alter_shirt_user_id'),
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='favorites',
            field=models.ManyToManyField(related_name='favorites_by', to='shirt.Shirt'),
        ),
    ]
